package io.openems.edge.ess.omni261;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "ESS OMNI 261", //
		description = "ESS OMNI 261 via Modbus TCP.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Read only", description = "If enabled, no remote control registers are written")
	boolean readOnly() default false;

	@AttributeDefinition(//
			name = "Device active power sign", //
			description = "Defines the sign convention of measured device active power.")
	DeviceActivePowerSign deviceActivePowerSign() default DeviceActivePowerSign.POSITIVE_CHARGE;

	@AttributeDefinition(name = "Capacity [Wh]", description = "Nominal battery capacity")
	int capacity() default 0;

	@AttributeDefinition(name = "Maximum charge power [W]", description = "Negative limit used by OpenEMS controllers")
	int maxChargePower() default 261_000;

	@AttributeDefinition(name = "Maximum discharge power [W]", description = "Positive limit used by OpenEMS controllers")
	int maxDischargePower() default 261_000;

	@AttributeDefinition(name = "Maximum apparent power [VA]")
	int maxApparentPower() default 261_000;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "ESS OMNI 261 [{id}]";
}

enum DeviceActivePowerSign {
	POSITIVE_CHARGE,
	POSITIVE_DISCHARGE
}
