package io.openems.edge.ess.omni430pcs;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "ESS OMNI 430 PCS", //
		description = "ESS OMNI 430 kW PCS via Modbus TCP.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Read only", description = "If enabled, no remote control registers are written")
	boolean readOnly() default false;

	@AttributeDefinition(//
			name = "Invert power sign", //
			description = "If enabled, measured active/reactive power values are inverted for monitoring.")
	boolean invertPowerSign() default false;

	@AttributeDefinition(name = "Capacity [Wh]", description = "Nominal battery capacity")
	int capacity() default 0;

	@AttributeDefinition(name = "Maximum charge power [W]", description = "Negative limit used by OpenEMS controllers")
	int maxChargePower() default 430_000;

	@AttributeDefinition(name = "Maximum discharge power [W]", description = "Positive limit used by OpenEMS controllers")
	int maxDischargePower() default 430_000;

	@AttributeDefinition(name = "Maximum apparent power [VA]")
	int maxApparentPower() default 430_000;

	@AttributeDefinition(//
			name = "Measure Modbus-ID", //
			description = "ID of Modbus bridge for Measuring Interface-1, usually TCP port 502.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(//
			name = "Adjust Modbus-ID", //
			description = "ID of Modbus bridge for Adjust Interface-6, usually TCP port 503.")
	String adjust_modbus_id() default "modbus1";

	@AttributeDefinition(name = "Modbus Unit-ID")
	int modbusUnitId() default 1;

	@AttributeDefinition(//
			name = "Measure Modbus target filter", //
			description = "This is auto-generated by 'Measure Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	@AttributeDefinition(//
			name = "Adjust Modbus target filter", //
			description = "This is auto-generated by 'Adjust Modbus-ID'.")
	String AdjustModbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "ESS OMNI 430 PCS [{id}]";
}
