package io.openems.edge.meter.selec.mfm383;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.common.types.MeterType;

@ObjectClassDefinition(//
		name = "Meter Selec MFM383", //
		description = "Implements the Selec MFM383/MFM383-C Modbus meter.")
@interface Config {

	public enum ReadRegisterType {
		INPUT_REGISTERS, HOLDING_REGISTERS
	}

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Meter-Type", description = "What is measured by this Meter?")
	MeterType type() default MeterType.GRID;

	@AttributeDefinition(name = "Invert", description = "Invert active/reactive power sign and swap production/consumption energy.")
	boolean invert() default false;

	@AttributeDefinition(name = "Read register type", description = "MFM383-C manual uses 30001 input-register addresses. Select holding-registers only if your device/gateway maps them to FC3.")
	ReadRegisterType readRegisterType() default ReadRegisterType.INPUT_REGISTERS;

	@AttributeDefinition(name = "Modbus-ID", description = "ID of Modbus bridge.")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus device.")
	int modbusUnitId() default 1;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Meter Selec MFM383 [{id}]";
}
